### ISSUE TITLE
starred功能没有起作用 [translation: starred feature is not working]

### ISSUE THREAD

**Issue by BranLiang** [ObsidianLabs/CKB-Studio#1]
Translation:
The starred feature in Explorer and TX transaction is not working in v0.5.0 macOS version. The starred account is missing in dropdown menu even if I use star feature. Rebooting is not working as well.

-----

使用的最新的0.5 mac版本ckb studio，但是使用过程中发现explorer和TX transaction部分的starred功能不起作用，即使相应的tab进行了star选择，依然不会显示在下拉菜单里面，重新启动也没有用

![image](https://user-images.githubusercontent.com/6628202/84557363-1ee35480-ad5d-11ea-9461-379bb5d72cb3.png)

![image](https://user-images.githubusercontent.com/6628202/84557366-286cbc80-ad5d-11ea-97b0-61db594b5aba.png)

**Comment by XinBLVD** [comment]
哈喽，您可以添加我们的微信或者Telegram群，群里会有开发者回答问题。微信号是eosstudioide，TG是
https://t.me/ckb_studio

bran <notifications@github.com>于2020年6月13日 周六10:04写道：

**Comment by qftgtr** [comment]
> 使用的最新的0.5 mac版本ckb studio，但是使用过程中发现explorer和TX transaction部分的starred功能不起作用，即使相应的tab进行了star选择，依然不会显示在下拉菜单里面，重新启动也没有用
> 
> ![image](https://user-images.githubusercontent.com/6628202/84557363-1ee35480-ad5d-11ea-9461-379bb5d72cb3.png)
> 
> ![image](https://user-images.githubusercontent.com/6628202/84557366-286cbc80-ad5d-11ea-97b0-61db594b5aba.png)

**Comment by leonlianght** [comment]
Fixed in https://github.com/ObsidianLabs/CKB-Studio/releases/tag/v0.6.0
